# Generated by Django 4.0.3 on 2022-04-11 02:58

from django.db import migrations, models
import info.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_info_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=info.models.info_image_file_path),
        ),
        migrations.AlterField(
            model_name='info',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='info', to='info.tag'),
        ),
    ]
