# Generated by Django 4.0.3 on 2022-04-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_alter_info_image_alter_info_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
